/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CalendarContainer: typeof import('./src/components/containers/CalendarContainer.vue')['default']
    CalendarFilters: typeof import('./src/components/filters/CalendarFilters.vue')['default']
    ChallengeFilter: typeof import('./src/components/filters/ChallengeFilter.vue')['default']
    CreateTaskContainer: typeof import('./src/components/containers/CreateTaskContainer.vue')['default']
    CreateTaskForm: typeof import('./src/components/CreateTaskForm.vue')['default']
    FixContainer: typeof import('./src/components/containers/FixContainer.vue')['default']
    GraphicContainer: typeof import('./src/components/containers/GraphicContainer.vue')['default']
    HistoryContainer: typeof import('./src/components/containers/HistoryContainer.vue')['default']
    HistoryFilters: typeof import('./src/components/filters/HistoryFilters.vue')['default']
    HistoryTable: typeof import('./src/components/HistoryTable.vue')['default']
    HomeContainer: typeof import('./src/components/containers/HomeContainer.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserFilter: typeof import('./src/components/filters/UserFilter.vue')['default']
    ViewFilters: typeof import('./src/components/filters/ViewFilters.vue')['default']
  }
}
